### ISSUE TITLE
How to do the interrupt?

### ISSUE THREAD

**Issue by gitvita28** [ldab/KXTJ3-1057#3]
I see this // Detection threshold, movement duration and polarity
            myIMU.intConf(123, 1, 10, HIGH);

But i don't understand.. how to use the interrupt to wake up the microcontroller?

**Comment by ssriblo** [comment]
Chip set INT pin HIGH. This pin is connected to MCU pin, so need to attach interrupt to this MCU pin. MCU can sleep and wake up when chip set HIGH level

**Comment by gitvita28** [comment]
Hi Leonardo,

Thank you for your answer, but I am not quite understanding. Could you
perhaps send an example of the accelerometer interrupt that you've tried
that works?

Sincerely appreciated!
Minerva
